[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['forge-std/=lib/forge-std/src/']

rpc_endpoints = { mainnet = "https://rpc.ankr.com/eth", optimism = "https://rpc.ankr.com/optimism" , fantom = "https://rpc.ankr.com/fantom", arbitrum = "https://rpc.ankr.com/arbitrum", bsc = "https://twilight-solemn-thunder.bsc.discover.quiknode.pro/c169ff08b41cd0597825491eb9d968a56bb9c09f/", moonriver = "https://moonriver.public.blastapi.io", gnosis = "https://rpc.ankr.com/gnosis", avax = "https://rpc.ankr.com/avalanche", polygon = "https://rpc.ankr.com/polygon", bsc_testnet = "https://data-seed-prebsc-2-s2.binance.org:8545", goerli = "https://rpc.ankr.com/eth_goerli"}

# See more config options https://github.com/gakonst/foundry/tree/master/config